### ISSUE TITLE
A suggestion about the bash shell script

### ISSUE THREAD

**Issue by telemachus** [colfrog/cx#6]
As written, the `cd` function you provide doesn’t respect `$?`. An example:

```shell
# If the user has not sourced your cx.sh script
cd nonexistentdirectory
echo $?
1

# If the user has sourced your cx.sh script
cd nonexistentdirectory
echo $?
0
```
In the second case, `$?` shows the success or failure of the call to `cxc -p "${PWD}"`.

I think the pattern you want is this, [as seen here for example](https://github.com/rvm/rvm/commit/f9aa3adebcca547924c8095fa7696967bd2d8d15#diff-b12491e60fcf1ac7ce080d3a20a0b2a5L19-R24):

```shell
  cd() {
      builtin cd $@
      result=$?
      cxc -p "${PWD}"
      return $result
  }
```

**Comment by colfrog** [comment]
Thank you!
